//DO NOT EDIT THIS FILE
//IT IS NOT TO BE REWRITTEN IN TYPESCRIPT

import { supabase } from "./supabase.js";

export const sessionState = {
  user: null,
  profile: null,
  plan: null,
  addons: [],
};

let resolveSessionReady;

export const sessionReady = new Promise((resolve) => {
  resolveSessionReady = resolve;
});

export async function initSession() {
  const {
    data: { session },
    error,
  } = await supabase.auth.getSession();

  if (error) {
    console.error("Session error:", error);
    resolveSessionReady();
    return;
  }

  const user = session?.user || null;

  if (!user) {
    resolveSessionReady();
    return;
  }

  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("*, plan (id, name, max_workspaces, max_members, price)")
    .eq("id", user.id)
    .single();

  if (profileError) {
    console.error("Profile error:", profileError);
    resolveSessionReady();
    return;
  }

  const { data: addonsData, error: addonsError } = await supabase
    .from("user_addons")
    .select(
      `
    addon_id,
    status,
    current_period_end,
    addons:addons (
      id,
      name
    )
  `,
    )
    .eq("user_id", user.id)
    .in("status", ["active", "trialing"]);

  const normalizedAddons = (addonsData || []).map((a) => {
    const addon = Array.isArray(a.addons) ? a.addons[0] : a.addons;

    return {
      id: a.addon_id,
      name: addon?.name || "Unknown addon",
      status: a.status,
      current_period_end: a.current_period_end,
    };
  });

  sessionState.user = user;
  sessionState.profile = profile;
  sessionState.plan = profile?.plan || null;
  sessionState.addons = normalizedAddons;

  resolveSessionReady();

  renderUserUI();
}

function renderUserUI() {
  const profileImg = document.querySelector(".profileImg");
  const profileAvatar = document.querySelector(".profileAvatar");
  const userName = document.querySelectorAll(".userName");
  const subscriptionType = document.getElementById("subscriptionType");

  if (!sessionState.user || !sessionState.profile) return;

  const email = sessionState.user.email;
  const [local, domain] = email.split("@");
  const shortEmail = `${local.slice(0, 9)}...@${domain}`;

  const planName = sessionState.plan?.name || "Free";

  if (userName) {
    userName.forEach((name) => {
      name.textContent =
        sessionState.profile.full_name === "User"
          ? shortEmail
          : sessionState.profile.full_name;
    });
  }

  const avatarUrl =
    sessionState.profile?.avatar_url ||
    "https://loghue.com/assets/images/default_profile.png";

  if (profileImg) {
    profileImg.src = avatarUrl;
    profileImg.className = "profileImg";
    profileImg.classList.add(planName);
  }

  if (profileAvatar) {
    profileAvatar.src = avatarUrl;

    document.querySelectorAll(".profileAvatarContainer").forEach((el) => {
      el.classList.add(planName);
    });
  }

  if (subscriptionType) {
    subscriptionType.textContent = planName;
  }
}

initSession();
