// DO NOT EDIT THIS FILE.
//IT IS NOT TO BE REWRITTEN IN TYPESCRIPT

import { supabase } from "../supabase.js";
import { actionMsg } from "https://app.loghue.com/js/utils/modals.js";
import { setButtonLoading } from "https://ui.scybud.com/js/ui.js";

//Signup funtion
async function signup(name, email, password) {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });

  if (error) {
    actionMsg(error.message, "error");
    return false;
  }

  actionMsg("Account created successfully!", "success");
  return true;
}

//Signup form
const signupForm = document.getElementById("signupForm");
if (signupForm) {
  signupForm.addEventListener("submit", async (e) => {
    e.preventDefault();

    const name = document.getElementById("userSignupNameInput").value.trim();
    const email = document.getElementById("userSignupEmailInput").value.trim();
    const password = document
      .getElementById("userSignupPasswordInput")
      .value.trim();
    const confirmPassword = document
      .getElementById("userSignupConfirmPasswordInput")
      .value.trim();

    if (!name) {
      actionMsg("Username is required", "warning");
      return;
    } else if (!password) {
      actionMsg("Password is required", "warning");
      return;
    } else if (!email) {
      actionMsg("Email is required", "warning");
      return;
    } else if (!confirmPassword) {
      actionMsg("Confirm your password", "warning");
      return;
    } else if (!email.includes("@")) {
      actionMsg("Please enter a valid email", "error");
      return;
    } else if (password != confirmPassword) {
      actionMsg("Passwords do not match", "error");
      return;
    } else if (password.length < 6) {
      actionMsg("Password must be at least 6 characters", "warning");
      return;
    }

    const button = signupForm.querySelector("button");
    setButtonLoading(button, true);

    try {
      const success = await signup(name, email, password);

      if (success) {
        // After successful signup:
        const params = new URLSearchParams(window.location.search);
        const redirectTo = params.get("redirect");

        if (redirectTo) {
          // Send them back to the invite page with the token
          window.location.href = decodeURIComponent(redirectTo);
        } else {
          // Default behavior
          window.location.href = "/tasks/";
        }
      }
    } finally {
      setButtonLoading(button, false);
    }
  });
}

//login funtion
async function login(email, password) {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    actionMsg(error.message, "error");
    return false;
  }

  return true;
}

//Login form
export function loginFuntion() {
  const loginForm = document.getElementById("loginForm");
  if (loginForm) {
    loginForm.addEventListener("submit", async (e) => {
      e.preventDefault();

      const email = document.getElementById("userLoginEmailInput").value.trim();
      const password = document
        .getElementById("userLoginPasswordInput")
        .value.trim();

      if (!email) {
        actionMsg("Email is required", "warning");
        return;
      }
      if (!password) {
        actionMsg("Password is required", "warning");
        return;
      }

      const button = document.getElementById("loginBtn");
      setButtonLoading(button, true);

      try {
        const success = await login(email, password);

        if (success) {
          // After successful login/signup:
          const params = new URLSearchParams(window.location.search);
          const redirectTo = params.get("redirect");

          if (redirectTo) {
            // Send them back to the invite page with the token
            window.location.href = decodeURIComponent(redirectTo);
          } else {
            // Default behavior
            window.location.href = "/tasks/";
          }
        }
      } finally {
        setButtonLoading(button, false);
      }
    });
  }
}
loginFuntion();

//signout
async function signout() {
  const { error } = await supabase.auth.signOut();

  if (error) {
    alert(error.message);
    return;
  }
  actionMsg("Logged out successfully!", "success");

  setTimeout(() => {
    window.location.href = "/auth";
  }, 3000);
}

export function attachSignoutEvents() {
  document.addEventListener("click", (e) => {
    const btn = e.target.closest("#logoutBtn");

    if (btn) {
      if (!confirm("Are you sure you want to logout?")) return;

      signout();
    }
  });
}

//OAuth funtion
function setupOAuthButton(buttonId, provider) {
  const btn = document.getElementById(buttonId);
  if (!btn) return;

  btn.addEventListener("click", async () => {
    setButtonLoading(btn, true);

    // Read redirect param from current URL
    const params = new URLSearchParams(window.location.search);
    const redirectTo = params.get("redirect");

    // Build callback URL with redirect param included
    const callbackUrl = "https://app.loghue.com/pages/auth/callback";

    if (redirectTo) {
      localStorage.setItem("post_login_redirect", redirectTo);
    }

    const { error } = await supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: callbackUrl,
      },
    });

    if (error) {
      actionMsg(`OAuth error: ${error.message}`);
      setButtonLoading(btn, false);
      return;
    }

    setButtonLoading(btn, false);
  });
}

//Implement OAuths

//Google Auth
setupOAuthButton("googleAuth", "google");
setupOAuthButton("microsoftAuth", "azure");
setupOAuthButton("githubAuth", "github");
