// DO NOT EDIT THIS FILE.
//IT IS NOT TO BE REWRITTEN IN TYPESCRIPT

import { supabase } from "../supabase.js";
import { actionMsg } from "https://app.loghue.com/js/utils/modals.js";

let loading = false;

const confirmCard = document.getElementById("confirmCard");
const redirectingState = document.getElementById("redirectingState");
const consentCheckbox = document.getElementById("consentCheckbox");
const continueBtn = document.getElementById("continueBtn");
const msg = redirectingState.querySelector(".msg");

let planId = null;

function showRedirecting() {
  confirmCard.classList.add("hidden");
  redirectingState.classList.remove("hidden");
}

async function bail(text, tone, redirectTo = "") {
  await actionMsg(text, tone);
  showRedirecting();
  msg.textContent = text;
  msg.classList.add(
    tone === "error" ? "error" : tone === "info" ? "warning" : "success",
  );
  loading = false;

  if (redirectTo) {
    setTimeout(() => {
      window.location.href = redirectTo;
    }, 1000);
  }
}

async function init() {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    window.location.href = "/auth?redirect=/billing";
    return;
  }

  const params = new URLSearchParams(window.location.search);
  planId = params.get("plan");

  if (!planId) {
    await bail("Missing plan ID. Redirecting...", "error", "index");
    return;
  }

  // Wire up the checkbox → enable button only when checked
  consentCheckbox.addEventListener("change", () => {
    continueBtn.classList.toggle("enabled", consentCheckbox.checked);
  });

  continueBtn.addEventListener("click", () => {
    if (!consentCheckbox.checked || loading) return;
    startUpgrade(session);
  });
}

async function startUpgrade(session) {
  if (loading) return;
  loading = true;
  showRedirecting();

  try {
    const { data, error } = await supabase.functions.invoke("create-checkout", {
      body: {
        id: planId,
        consent: consentCheckbox.checked,
      },
      headers: {
        Authorization: `Bearer ${session.access_token}`,
      },
    });

    if (error?.message.includes("Already purchased")) {
      await bail("You already have this plan", "info");
      return;
    }

    if (error) {
      console.error(error);
      await bail("Failed to start checkout. Redirecting...", "error", "index");
      return;
    }

    // CASE 1: Stripe checkout
    if (data?.url) {
      window.location.href = data.url;
      return;
    }

    // CASE 2: instant update (addon/plan modify)
    if (data?.success) {
      await bail(data.message || "Updated successfully!", "success");
      return;
    }

    console.error("Unexpected response:", data);
    await bail("Unexpected server response. Redirecting...", "error");
  } finally {
    loading = false;
  }
}

init();
